# site settings
title: guptamukund22
subtitle: by HTML5 UP
email: guptamukund22@gmail.com
description: SOB'24 python-bitcoin-utils | IIT Jodhpur | Open Source Enthusiast
baseurl: "" # the subpath of your site, e.g. /blog
url: guptamukund22.github.io
author: Mukund
street_address:
city: New Delhi
state: Delhi
zip_code: 110096
country: India
phone:

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url: https://github.com/guptamukund22
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url: https://www.linkedin.com/in/mukund-gupta-b93a252a0/
pinterest_url:
slack_url:
twitter_url: 

# build settings
markdown: kramdown

sass:
  style: compressed

plugins:
  - jekyll-feed
